import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  Dessert,
  Footer,
  Header,
  Highlight,
  MainMenu,
  SaladSnack,
  SaleMenu,
  StatusCards,
} from "@/components/homePage";
import { Box, Stack } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Food delivery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pinecone.svg" />
      </Head>
      <main>
        <Stack>
          <Box>
            <Header />
          </Box>
          <Box>
            <Highlight />
          </Box>
          <Box>
            <StatusCards />
          </Box>
          <Box>
            <SaleMenu />
          </Box>
          <Box>
            <MainMenu />
          </Box>
          <Box>
            <SaladSnack />
          </Box>
          <Box>
            <Dessert />
          </Box>
          <Box>
            <Footer />
          </Box>
        </Stack>
      </main>
    </>
  );
}
